name: Release

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ master ]
    types:
      - completed

jobs:
  package:
    name: package

    runs-on: ubuntu-latest
    container: docker://node:latest

    steps:
      - uses: actions/checkout@v2

      - name: Download lib from build job
        uses: actions/download-artifact@v2
        with:
          name: lib
          path: ./lib

      - name: 🧳 pack
        run: make package